# -*- coding: utf-8 -*-
"""Copy of HW 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KRIKY3D_rPQfkkgRETqxDr67ACVJWkKs
"""

import pandas as pd
from sklearn.datasets import load_iris
import numpy as np
iris = load_iris(as_frame=True)
df = iris.frame
df["species"] = df["target"].map(dict(enumerate(iris.target_names)))
df = df.drop(columns=["target"])


#3a
print("First 5 rows:")
display(df.head(5))
print("Shape:", df.shape)
print("Columns:", list(df.columns))
print("\nData types:")
print(df.dtypes)


#3b
df_small = df[["sepal length (cm)", "petal length (cm)", "species"]]
display(df_small.head(5))


#3c
df_virg = df_small[(df_small["species"] == "virginica") & (df_small["petal length (cm)"] > 5.0)]
display(df_virg.head(10))


#3d
print("Mean Sepal Length (cm):", df["sepal length (cm)"].mean())
print("Maximum Petal Width (cm):", df["petal width (cm)"].max())
print("Minimum Petal Length (cm):", df["petal length (cm)"].min())


#3e
df.groupby("species").agg({
    "sepal length (cm)": ["mean"],
    "sepal width (cm)": ["mean"],
    "petal length (cm)": ['mean'],
    "petal width (cm)": ['mean']
})