# -*- coding: utf-8 -*-
"""Exam_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IRSKNb8_r_jlscHc2wi0JnW-aMPdvuvc
"""

import numpy as np
import matplotlib.pyplot as plt

#1a Compute the matrix product AB. State the size of AB
A = np.array([
    [1, -2, 0],
    [3, 1, 4]
])

B = np.array([
    [2, 1],
    [-1, 3],
    [5, 0]
])

C = np.array([
    [1, 2],
    [0, -1]
])

print(A@B)

#1b  Let where I is the identity matrix and 0 is the zero matrix. Compute M2 using block matrix multiplication (do not expand M into a full 4 × 4 matrix until the end)
M = np.block([
    [C, np.eye(2)],
    [np.zeros((2, 2)), C]
])

print(M)

print(M@M)

M2 = np.linalg.matrix_power(M, 2)
print(M2)

#1c Compute the Frobenius norm ∥AB∥F
F = A@B
print(np.linalg.matrix_norm(F))

#1d Compute the induced 1-norm of C
norm1 = np.linalg.norm(C, 1)
print(norm1)

#1e Verify whether {v1,v2,v3} is linearly independent. (Hint: form the matrix V = [v1 v2 v3] and check det(V) or rank(V))
v1 = np.array([
    [1],
    [0],
    [1]
])

v2 = np.array([
    [2],
    [1],
    [3]
])

v3 = np.array([
    [0],
    [1],
    [1]
])

V = np.block([
    [v1, v2, v3]
])

print(np.linalg.det(V))

print(np.linalg.matrix_rank(V))

rank = np.linalg.matrix_rank(V)

import math

#2 The surface of the earth is reasonably approximated as a sphere with radius R = 6367.5 km. A location on the earth’s surface is traditionally given by its latitude θ
#and its longitude λ, which correspond to angular distance from the equator and prime meridian, respectively. The distance through the earth between two locations
#(3-vectors) a and b is ∥a−b∥. The distance along the surface of the earth between points a and b is R∠(a,b). Find these two distances between Palo Alto and Beijing, with
#latitudes and longitudes given below.
R = 6367.5
beijing_theta = 39.914*(math.pi/180)
beijing_lambda = 116.392*(math.pi/180)

a = np.array([
    [R*np.sin(beijing_lambda)*np.cos(beijing_theta)],
    [R*np.cos(beijing_lambda)*np.cos(beijing_theta)],
    [R*np.sin(beijing_theta)]
  ])

palo_alto_theta = 37.429*(math.pi/180)
palo_alto_lambda = -122.138*(math.pi/180)

b = np.array([
    [R*np.sin(palo_alto_lambda)*np.cos(palo_alto_theta)],
    [R*np.cos(palo_alto_lambda)*np.cos(palo_alto_theta)],
    [R*np.sin(palo_alto_theta)]
  ])

diff = a - b
print("Distance through the Earth: ")
print(np.linalg.matrix_norm(diff))
dot = a.T @ b
angle = math.acos(dot / (np.linalg.norm(a) * np.linalg.norm(b)))
print("Distance along the surface of the Earth: ")
print(R*angle)

#3a  Suppose a1, ..., ak are linearly independent. (We make no assumptions about the vectors b1, ..., bk) Can we conclude that the stacked vectors c1, ..., ck are
#linearly independent?
a1 = np.array([
    [1],
    [2]
])

a2 = np.array([
    [5],
    [5]
])

A = np.block([
    [a1, a2]
])

print(np.linalg.det(A))

#A columns are linearly independent

b1 = np.array([
    [1],
    [2]
])

b2 = np.array([
    [3],
    [4]
])

B1 = np.block([
    [b1, b2]
])

print(np.linalg.det(B1))

#B1 columns are linearly independent

b3 = np.array([
    [1],
    [2]
])

b4 = np.array([
    [2],
    [4]
])

B2 = np.block([
    [b3, b4]
])

print(np.linalg.det(B2))

#B2 columns are linearly dependent

c1 = np.block([
    [a1],
    [b1]
])

c2 = np.block([
    [a2],
    [b2]
])

C = np.block([
    [c1, c2]
])

print(np.linalg.matrix_rank(C))

#C columns are linearly independent

c1 = np.block([
    [a1],
    [b3]
])

c2 = np.block([
    [a2],
    [b4]
])

C2 = np.block([
    [c1, c2]
])

print(np.linalg.matrix_rank(C2))

#C columns are linearly independent

#3b Now suppose that a1, ..., ak are linearly dependent. (Again, with no assumptions about b1, ..., bk) Can we conclude that the stacked vectors c1, ..., ck are linearly
#dependent?
a1 = np.array([
    [1],
    [2]
])

a2 = np.array([
    [2],
    [4]
])

A = np.block([
    [a1, a2]
])

print(np.linalg.det(A))

#A columns are linearly dependent

b1 = np.array([
    [1],
    [2]
])

b2 = np.array([
    [3],
    [4]
])

B1 = np.block([
    [b1, b2]
])

print(np.linalg.det(B1))

#B1 columns are linearly independent

c1 = np.block([
    [a1],
    [b1]
])

c2 = np.block([
    [a2],
    [b2]
])

C = np.block([
    [c1, c2]
])

print(np.linalg.matrix_rank(C))

#C columns are linearly independent

#5b
T = 5
r = 0.1

c = np.array([
    [100],
    [-30],
    [50],
    [0],
    [-80]
])

b1 = 100
b2 = (1+r)*b1 + (-30)
b3 = (1+r)*b2 + 50
b4 = (1+r)*b3 + 0
b5 = (1+r)*b4 + (-80)

b = np.array([
    [b1],
    [b2],
    [b3],
    [b4],
    [b5]
])

print(b)