# -*- coding: utf-8 -*-
"""Exam 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PVNQ2-__AXTfHD5_9XMmeq6o6Jk1PKhC
"""

#2a.  Let X ∼ Poisson(λ) with λ = 20. Simulate 10,000 samples from this distribution
import matplotlib.pyplot as plt
from scipy.stats import poisson

lam = 20
x = poisson.rvs(mu=lam, size = 10000)


#b.  Simulate 10,000 samples from the normal distribution Y ∼ N(20,20)

from scipy.stats import norm

mu = 20
sigma = 20

y = norm.rvs(mu, sigma, size = 10000)


#c. Plot histograms of the Poisson and normal samples on the same scale, and compare their shapes. You may visualize these as follows:

plt.figure(figsize=(8,6))
plt.hist(x, bins=30, density=True, alpha=0.6, label=f"Poisson({lam}) samples")
plt.hist(y, bins=30, density=True, alpha=0.4, label=f"Normal({lam}, {lam}) samples")

plt.xlabel("Value")
plt.ylabel("Density")
plt.title("Poisson vs Normal Approximation")
plt.legend()
plt.grid(True)
plt.show()


#d. Compute the sample mean and sample variance of both simulated datasets
print("Poisson sample mean and variance: ")
print(x.mean())
print(x.var())
print("Normal sample mean and variance: ")
print(y.mean())
print(y.var())

#e.  Explain why the normal approximation to a Poisson distribution improves as λ becomes large

#On Paper


#f.  Repeat parts (a)-(e) with λ = 5, and comment on why the approximation is worse in this case
lam = 5
x = poisson.rvs(mu=lam, size = 10000)
y = norm.rvs(5, 5, size = 10000)
plt.figure(figsize=(8,6))
plt.hist(x, bins=30, density=True, alpha=0.6, label=f"Poisson({lam}) samples")
plt.hist(y, bins=30, density=True, alpha=0.4, label=f"Normal({lam}, {lam}) samples")

plt.xlabel("Value")
plt.ylabel("Density")
plt.title("Poisson vs Normal Approximation")
plt.legend()
plt.grid(True)
plt.show()

print("Poisson sample mean and variance: ")
print(x.mean())
print(x.var())


# g.  Now let Z ∼ Gamma(α,θ) with shape α = 25 and scale θ = 2. Simulate 10,000 samples from this gamma distribution

from scipy.stats import uniform, expon, gamma

alpha = 25
theta = 2

sample_gamma = gamma.rvs(a = alpha, scale = theta, size = 10000)


#h. Approximate this gamma distribution by a normal distribution with the same mean and variance: N(αθ,αθ^2).

mu = alpha*theta
sigma = alpha*(theta**2)

z = norm.rvs(mu, sigma, size = 10000)


#i. Plot histograms of the gamma and normal samples on the same scale, and compare their shapes.

plt.figure(figsize=(8,6))
plt.hist(sample_gamma, bins=30, density=True, alpha=0.6, label=f"Gamma({alpha}, {theta}) samples")
plt.hist(z, bins=30, density=True, alpha=0.4, label=f"Normal({mu}, {sigma}) samples")

plt.xlabel("Value")
plt.ylabel("Density")
plt.title("Gamma vs Normal Approximation")
plt.legend()
plt.grid(True)
plt.show()


#j. Repeat parts (g)-(i) with α = 4 and θ = 2, and explain why the approximation becomes less accurate.

alpha = 4
theta = 2

sample_gamma = gamma.rvs(a = alpha, scale = theta, size = 10000)

mu = alpha*theta
sigma = alpha*(theta**2)

z = norm.rvs(mu, sigma, size = 10000)

plt.figure(figsize=(8,6))
plt.hist(sample_gamma, bins=30, density=True, alpha=0.6, label=f"Gamma({alpha}, {theta}) samples")
plt.hist(z, bins=30, density=True, alpha=0.4, label=f"Normal({mu}, {sigma}) samples")

plt.xlabel("Value")
plt.ylabel("Density")
plt.title("Gamma vs Normal Approximation")
plt.legend()
plt.grid(True)
plt.show()


#k. Summarize what features of a distribution make a normal approximation more effective

#On paper

#3a.  Load the dataset in Python and extract the variables studytime and G3.
from ucimlrepo import fetch_ucirepo
import pandas as pd
import matplotlib.pyplot as plt

# fetch dataset
student_performance = fetch_ucirepo(id=320)
X = student_performance.data.features
y = student_performance.data.targets
# combine features and target
df = pd.concat([X, y], axis=1)
# keep only study time and final grade
df_q3 = df[["studytime", "G3"]].copy()


#b. Display the first few rows of the data.
df_q3.head(5)


#c. Create a scatter plot of final grade versus study time.
df_q3.plot(x="studytime", y="G3", kind="scatter")
plt.title("Final Grade vs Study Time")
plt.ylabel("Final Grade")
plt.xlabel("Study Time")
plt.show()


#d. Compute the sample mean and variance of both variables.
print("Studytime:")
print(df_q3["studytime"].mean())
print(df_q3["studytime"].var())
print("Final Grade:")
print(df_q3["G3"].mean())
print(df_q3["G3"].var())
var1 = df_q3["studytime"].var()
var2 = df_q3["G3"].var()
sd1 = var1**0.5
sd2 = var2**0.5


#e. Compute the sample covariance between studytime and G3.
print(df["studytime"].cov(df["G3"]))
cov = df["studytime"].cov(df["G3"])


#f. Compute the sample correlation between studytime and G3.
print(df["studytime"].corr(df["G3"]))
print(cov/(sd1*sd2))


#g. Interpret the sign and magnitude of the correlation.

#On Paper


#h. Explain why this relationship should be interpreted carefully, given that studytime is an ordinal variable.

#On Paper


#i. Briefly explain what the joint distribution of (X, Y) tells us beyond the marginal distributions.

#On Paper