# -*- coding: utf-8 -*-
"""HW4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14bKoSQmEuegUyvXoAGSxtBaimNbO-wsK
"""

#1a. Load the digits dataset in Python and form the data matrixX

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import mean_squared_error
digits = load_digits()
X_raw = digits.data.astype(float)
y = digits.target
feature_names = digits.feature_names
target_names = digits.target_names

print('Data:\n', X_raw[:5])
print("Features:", feature_names)
print("Classes:", target_names)


#b. Center the data by subtracting the sample mean of each feature

feature_means = np.mean(X_raw, axis=0)
X_center = X_raw - feature_means
print(np.round(X_center.mean(axis=0), 5))


#c. Compute the singular value decomposition (SVD) of the centered data matrix

U, sigma, Vt = np.linalg.svd(X_center, full_matrices=False)


#d.  Explain briefly how principal component analysis (PCA) is related to the SVD of the centered data matrix.

#Answer on paper


#e.  Compute the proportion of variance explained by the first 2, 5, 10, and 20 principal components.

singular_values_squared = sigma**2
total_variance = np.sum(singular_values_squared)
print(np.sum(singular_values_squared[:2])  / total_variance)
print(np.sum(singular_values_squared[:5])  / total_variance)
print(np.sum(singular_values_squared[:10]) / total_variance)
print(np.sum(singular_values_squared[:20]) / total_variance)


#f. Project the data onto the first two principal components and create a scatter plot colored by the digit labels.

Z = X_center @ Vt[:2].T

plt.figure(figsize=(8,6))
for cls in np.unique(y):
    plt.scatter(Z[y==cls, 0], Z[y==cls, 1], label=digits.target_names[cls])

plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("PCA: PC1 vs PC2")
plt.legend()
plt.grid(True)
plt.show()


#g. Select one image with number “5”, add Gaussian noise to it, and display the noisy image. Denoise the image using rank-k approximations with k = 5, 10, and 20.

rng = np.random.default_rng(12345)
idx = 5
x_original = X_raw[idx]
x_noisy = x_original + rng.normal(loc=0.0, scale=4.0, size=x_original.shape)

ks = [5, 10, 20]
denoised_images = []
mses = []

for k in ks:
    # Rank-k approximation basis
    Vk = Vt[:k, :]          # shape (k, 64)

    # Project noisy image onto first k PCs
    coeffs = x_noisy @ Vk.T  # shape (k,)

    # Reconstruct
    x_denoised = coeffs @ Vk  # shape (64,)

    # Clip to valid pixel range
    x_denoised = np.clip(x_denoised, 0, 16)

    denoised_images.append(x_denoised)


    mse = mean_squared_error(x_original, x_denoised)
    mses.append(mse)

# Plot original, noisy, and denoised images
n_cols = len(ks) + 2
plt.figure(figsize=(2.5 * n_cols, 3))

plt.subplot(1, n_cols, 1)
plt.imshow(x_original.reshape(8, 8), cmap='gray')
plt.title("Original")
plt.axis('off')

plt.subplot(1, n_cols, 2)
plt.imshow(x_noisy.reshape(8, 8), cmap='gray')
plt.title("Noisy")
plt.axis('off')

for i, (k, img_k) in enumerate(zip(ks, denoised_images), start=3):
    plt.subplot(1, n_cols, i)
    plt.imshow(img_k.reshape(8, 8), cmap='gray')
    plt.title(f"k = {k}")
    plt.axis('off')

plt.tight_layout()
plt.show()

print("MSEs:", mses)


#h. Compare the original, noisy, and denoised images, and explain how the choice of k affects the reconstruction quality

#On Paper

#4a. Load the tips dataset in Python and extract the variable corresponding to tip amount.

import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px
df = px.data.tips()
tips = df["tip"].to_numpy()


#b. Write down the likelihood function L(λ) for the sample X1,...,Xn.

#On Paper


#c. Derive the log-likelihood function ℓ(λ).

#On Paper


#d. Compute the maximum likelihood estimator λ-hat analytically.

#On Paper


#e. Evaluate λ-hat numerically using the dataset.

n = len(tips)
tips[:5]
lambda_hat = n / np.sum(tips)
print(lambda_hat)
lambda_hat2 = 1 / np.mean(tips)
print(lambda_hat2)


#f. Use the fitted model to compute the estimated mean tip amount.

mean_estimated = 1 / lambda_hat
print(mean_estimated)


#g. Plot a histogram of the observed tip amounts and overlay the fitted exponential density.

x = np.linspace(0, tips.max(), 200)
fitted_pdf = lambda_hat * np.exp(-lambda_hat * x)

plt.figure(figsize=(8,5))
plt.hist(tips, bins=20, density=True, alpha=0.6, color='skyblue', label="Observed tips")
plt.plot(x, fitted_pdf, 'r-', linewidth=2, label="Fitted exponential PDF")
plt.xlabel("Tip amount")
plt.ylabel("Density")
plt.title("Histogram of Tips with Fitted Exponential Density")
plt.legend()
plt.show()


#h. Compare the sample mean with the mean implied by the fitted exponential model.

sample_mean = np.mean(tips)
model_mean = 1 / lambda_hat

sample_mean, model_mean


#i. Based on the histogram and fitted density, comment on whether the exponential model appears to be a reasonable choice for this dataset.

#On Paper

#5a. Load the dataset into Python as a pandas data frame. Display the first five rows and the column names.
!pip install palmerpenguins

from palmerpenguins import load_penguins

df = load_penguins()
print(df.head(5))


#b. Report the number of rows and columns in the data frame. Compute the number of missing values in each column.

print(df.shape)
print("Missing values in each column\n")
print(df.isna().sum())


#c. Keep only the columns species, island, sex, bill length mm, bill depth mm, flipper length, body_mass_g

cols_to_keep = [
    "species",
    "island",
    "sex",
    "bill_length_mm",
    "bill_depth_mm",
    "flipper_length_mm",
    "body_mass_g"
]

df = df[cols_to_keep]
print(df.head())


#d. Remove rows with missing values in any of the columns listed above.

df_new = df.dropna().copy()
print(df_new)


#e. Create two new columns: body_mass_kg = body_mass_g/1000, bill_ratio = bill_length_mm/bill_depth_mm

df_new["body_mass_kg"] = df_new["body_mass_g"]/1000
df_new["bill_ratio"] = df_new["bill_length_mm"] / df_new["bill_depth_mm"]
print(df_new)


#f. Filter the data to include only penguins from the islands Biscoe and Dream.

df_filter = df_new[(df_new['island'] == 'Biscoe') | (df_new['island'] == 'Dream')]
print(df_filter)


#g. Using the filtered data, compute a summary table by species containing:
#• the number of penguins,
#• the mean body mass in kilograms,
#• the mean flipper length,
#• the mean bill ratio.

print(df_filter.groupby("species").agg({
    "species": "count",
    "body_mass_kg": "mean",
    "flipper_length_mm": "mean",
    "bill_ratio": "mean"
}))


#h. Find the five heaviest penguins in the filtered data and display their species, island, sex, and body mass.

print(df_filter.sort_values("body_mass_kg", ascending=False) \
         .head(5)[["species", "island", "sex", "body_mass_kg", "body_mass_g"]])


#i. Make a boxplot of body_mass_kg grouped by species, and briefly comment on any visible differences among species.

df_filter.boxplot(column="body_mass_kg", by="species")
plt.title("Body Mass (kg) by Species")
plt.suptitle("")
plt.ylabel("Body Mass (kg)")
plt.show()