# -*- coding: utf-8 -*-
"""HW 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dzHFCZ96Odc84Bj4hSQhFRWIuVI7Ul9
"""

#2a
from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

wine = load_wine()
X = wine.data
y = wine.target


#2b
print(X.size)
print(y.size)
print(wine.feature_names)
print(wine.target_names)


#2c
X_std = StandardScaler().fit_transform(X)
print('X_std:\n', X_std[:5])


#2d
pca_full = PCA(n_components=X.shape[1])
Z_full = pca_full.fit_transform(X_std)


#2e
expl_var = pca_full.explained_variance_ratio_
cum_expl_var = np.cumsum(expl_var)

print("\nExplained variance ratio:")
print(expl_var)

print("\nCumulative explained variance ratio:")
print(cum_expl_var)


#2f
pc_80 = np.argmax(cum_expl_var >= 0.80) + 1
pc_90 = np.argmax(cum_expl_var >= 0.90) + 1

print("\nMinimum PCs for 80% variance:", pc_80)
print("Minimum PCs for 90% variance:", pc_90)


#2g
pca2 = PCA(n_components=2)
Z = pca2.fit_transform(X_std)


#2h
plt.figure(figsize=(8,6))
for cls in np.unique(y):
    plt.scatter(Z[y==cls, 0], Z[y==cls, 1], label=wine.target_names[cls])

plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("PCA: PC1 vs PC2")
plt.legend()
plt.grid(True)
plt.show()


#2i
loadings = pca2.components_.T
loading_df = pd.DataFrame(loadings,
                          columns=["PC1", "PC2"],
                          index=wine.feature_names)

print("\nLoading vectors for PC1 and PC2:")
print(loading_df)

#2j
#PCA reveals clear structure in the Wine dataset. The first few principal components capture most of the variance with it being 55.4% with the first two.
#The scatter plot shows that the three wine classes form distinct clusters. The loading vectors show that PC1 is driven mainly by falvanoids and phenols,
#while PC2 is driven by color and alcohol.

#3a, 3b, 3c, 3d, 3e, 3f, 3g

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_olivetti_faces
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import mean_squared_error

# load data and add noise
faces = fetch_olivetti_faces(shuffle=True, random_state=42)
image = faces.images[0]

np.random.seed(42)
noise_level = 0.20
noisy_image = image + noise_level * np.random.randn(*image.shape)
noisy_image = np.clip(noisy_image, 0, 1)

X_orig  = image
X_noisy = noisy_image

ks = [5, 10, 20, 30, 40, 50]
denoised_images = []
mses = []

for k in ks:
    tsvd = TruncatedSVD(n_components=k, random_state=0)
    Z = tsvd.fit_transform(X_noisy)
    X_denoised = tsvd.inverse_transform(Z)
    X_denoised = np.clip(X_denoised, 0.0, 1.0)

    denoised_images.append(X_denoised)

    mse = mean_squared_error(X_orig, X_denoised)
    mses.append(mse)

# plot original, noisy, denoised
n_cols = len(ks) + 2
plt.figure(figsize=(2.5 * n_cols, 3))

plt.subplot(1, n_cols, 1)
plt.imshow(image, cmap='gray')
plt.title("Original")
plt.axis('off')

plt.subplot(1, n_cols, 2)
plt.imshow(noisy_image, cmap='gray')
plt.title("Noisy")
plt.axis('off')

for i, (k, img_k) in enumerate(zip(ks, denoised_images), start=3):
    plt.subplot(1, n_cols, i)
    plt.imshow(img_k, cmap='gray')
    plt.title(f"k = {k}")
    plt.axis('off')

plt.tight_layout()
plt.show()

for k, mse in zip(ks, mses):
    print(f"k = {k:2d}, MSE = {mse:.6f}")